### ISSUE TITLE
 Error : gekko/core/candleManager.js:560   this.days[mom.dayString].handle.find

### ISSUE THREAD

**Issue by unstephenk** [kuzetsa/gekko#5]
waited two days only to get an error from gekko.  I have no idea what could have gone wrong. I want to reinstall the gekko folder but is there a way to use my old database storages? I am using cex.io and trading BTC and GHS. I have a balance in both.

/var/www/html/gekko/core/candleManager.js:560
  this.days[mom.dayString].handle.find({
                                  ^
TypeError: Object false has no method 'find'
    at Manager.getCandles (/var/www/html/gekko/core/candleManager.js:560:35)
    at bound [as getCandles](/var/www/html/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at iterator (/var/www/html/gekko/core/candleManager.js:516:10)
    at bound (/var/www/html/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at /var/www/html/gekko/node_modules/async/lib/async.js:227:13
    at /var/www/html/gekko/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)
    at _each (/var/www/html/gekko/node_modules/async/lib/async.js:32:24)
    at async.each (/var/www/html/gekko/node_modules/async/lib/async.js:110:9)
    at _asyncMap (/var/www/html/gekko/node_modules/async/lib/async.js:226:9)

**Comment by kuzetsa** [comment]
If there is any gap in your history data, it's treated as invalid, and so you won't be able to use it.

The error message you have is relating to bad historical data.

Could you please delete your history data completely?

I have continuous data for cex.io going back to 2014 June 26, and once you manage to get your gekko instance correctly configured I'd be happy to assist you with installing more historical data.

To assist with troubleshooting bad configuration, please post your config.js on http://gist.github.com/ (_obfuscate or ommit your API keys_) and update this issue with a link to the gist.

**Comment by unstephenk** [comment]
I removed the entire gekko folder and cloned it directly from here. This issue did not appear again.

**Comment by kuzetsa** [comment]
Oh, I guess this issue went away. That's good. add a comment if it comes back, but for now I'm closing this one.
